freifunk/projects.freifunk.net-contents

collections/_projects/freifunk_openwifi_wardiver_app.md

Signed-off-by: Jan-Tarek Butt <tarek@ring0.de>
This project is related to the last two GSoC projects from me.
https://github.com/freifunk-gluon/gluon/pull/1226
https://github.com/freifunk-gluon/gluon/pull/1211
https://github.com/freifunk-gluon/gluon/pull/1201

Openwifi.su: add new openWLANmap APP project

---

collections/_projects/local_network_phone_app.md

Let me know if something is missing / can be improved.

add local phone app proposal

---

collections/_projects/freifunk_openwifi_wardiver_app.md

* Set markdown links for maintainers.
* add more detail information's

freifunk_openwifi_wardiver_app.md: spellcheck and additions

---

collections/_projects/qaul.net_DNS-Service.md
collections/_projects/qaul.net_Service-Protocols.md

The first two tasks: 
* DNS Service
* Network independent service protocol

qaul.net GSoC tasks

---

collections/_projects/qaul.net_EmberJS-GUI.md

Implement the qaul.net HTML5 using EmberJs.

qaul.net EmberJs GUI implementation

---

collections/_projects/web-interface-bmx7-semtor.md

add bmx7 semtor web interface project

---

collections/_projects/mptcp-ksb.md

Following last year project, we need a port of KSB to a more recent kernel.

add mptcp and KSB port

---

collections/_projects/freifunk_meshenger.md

This is a project proposal meant as a follow-up for the GSoC 2018 Local Phone App project.

add local phone follow-up project

---

collections/_projects/freifunk_meshenger.md

Some description improvement to help students.

meshenger: improve description

---

collections/_projects/openwrt_firmware_selector.md

Hi,
a proposal of a GSoC project for OpenWrt
Context: https://forum.openwrt.org/t/firmware-wizard/9039/49

selector: add project

---

collections/_projects/openwrt_ppa.md

add openwrt PPA

---

collections/_projects/openwrt_firmware_wizard.md

@aparcar volunteers to help out as a second mentor for this project.

add mentor project

---

collections/_projects/freifunk_meshenger.md

Some refinement after student feedback.

meshenger: remove description

---

collections/_projects/qaul.net_http-api-core.md
collections/_projects/qaul.net_user-network-simulator.md

The two projects for GSoC 2019 from qaul.net

qaul.net GSoC projects 2019

---

collections/_projects/qaul.net_http-api-core.md
collections/_projects/qaul.net_user-network-simulator.md

mentor names pointed to other people's github repositories :-/

fixed mentor names to correct github id's

---

collections/_projects/qaul.net_http-api-core.md
collections/_projects/qaul.net_user-network-simulator.md

Added github usses for projects.

added issues for qaul.net projects

---

collections/_projects/libremesh-AI-log-filtering.md
collections/_projects/libremesh-cable-purpose-autodection.md
collections/_projects/libremesh-wireless-serial-debugging.md

This pull request is still work in progress,  comments are welcome, I'll remove WIP from the PR title when I think it is ready to be considered form merging

Add LibreMesh ideas

---

collections/_projects/freifunk-meshnet-evaluation.md

An idea for GSoC 2020. Testing mesh routing protocols and creating nice and hopefully comparable graphs.

add freifunk meshnet evaluation for GSoC 2020

---

collections/_projects/vxlan-VPN.md

Signed-off-by: Jan-Tarek Butt <tarek@ring0.de>

Add Projekt vxlan-VPN

---

collections/_projects/evernet_digital_Freifunk_twin.md

Signed-off-by: Thomas Huehn <thomas.huehn@hs-nordhausen.de>

add new Evernet project: Freifunk CI - Digital Mesh-Network Twin

---

collections/_projects/irdest-basic-android-app.md
collections/_projects/irdest-internet-overlay.md

Project rename

---

.github/workflows/deploy-projects.yaml
collections/_projects/openwrt_migrate_luci.md

@aparcar I added an idea for migration luci apps to client side api
Signed-off-by: Andreas Bräu <ab@andi95.de>

add new idea for luci migration

---

collections/_projects/freifunk-call-a-friend.md

A plan to create a new Meshenger release. The App and idea behind it are just too good to not push forward.

Add "Call A Friend"  project

---

collections/_projects/freifunk-on-satellites.md

The task for the student would be to create a test tsetup to test mesh routing protocols (batman-adv, babel, ..) with satellites.

Add "Ad-Hoc Mesh Networks with Satellites" project idea

---

collections/_projects/freifunk-call-a-friend.md

Some improvement for the text.

update meshenger project text

---

collections/_projects/olsrd_build_and_release_system.md

Look @polynomialdivision :)
Signed-off-by: Andreas Bräu <ab@andi95.de>

add proposal for olsr

---

collections/_projects/openwrt_ppa.md

OpenWRT PPA: add links to OBS package format

OpenWRT PPA: add links to OBS package format

---

collections/_projects/evernet_minstrel_rate_control_in_userspace.md

Signed-off-by: Thomas Huehn <thomas.huehn@hs-nordhausen.de>

add new project: Minstrel_HT rate control in user space

---

collections/_projects/evernet_tx-power-control_in_WiFi_networks.md

Signed-off-by: Thomas Huehn <thomas.huehn@hs-nordhausen.de>

add transmit power control topic to FFF_GSoC

---

collections/_projects/transmit_power_control_for_mediatek_ieee_802_11ac_wifi_chips.md

Signed-off-by: Thomas Huehn <thomas.huehn@hs-nordhausen.de>
Signed-off-by: Jonas Jelonek <jelonek.jonas@gmail.com>

Add 'Transmit Power Control for Mediatek' project

---

collections/_projects/joint-power-rate-control-in-uspace.md

GSoC '23 project on behalf of Thomas Hühn (thuehn)

Added 'Joint Power and Rate Control in User space' Project

---

collections/_faq/999_who-we-are.md
collections/_projects/freifunk_goes_100G.md
collections/_projects/libremesh-automation_monitoring.md

Some web servers of external links response with a HTTP status code 301 or 404.
This pull request updates those external links.

Update external links
